---
label: Produit
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: boolean
  name: published
  label: published
- type: text
  name: designer
  label: designer
- name: cover_image
  type: image_gallery
  config: {}
  label: cover_image
  description: Ne mettre qu'une seule image en 500x500px
- name: collection
  type: select
  default: Mobilier urbain
  config:
    required: true
    options:
    - Mobilier urbain
    - Hook
    - Signalétique
    source:
      type: simple
      section: 
      file: 
      path: 
  label: collection
- type: text
  name: sub_category
  label: sub_category
- name: gamme
  type: text
  config:
    required: true
  label: gamme
- type: text
  name: category
  label: category
- type: image_gallery
  name: caroussel
  label: caroussel
- name: filaire
  type: image_gallery
  config: {}
  label: Filaire
- name: reference
  type: text
  config:
    required: false
  label: Référence
  description: Référence article (SAGE commerce)
  hidden: false
- type: text
  name: materiau
  label: materiau
- type: text
  name: poids
  label: poids
- type: text
  name: dimensions
  label: dimensions
- name: format
  type: select
  default: ''
  config:
    required: false
    options:
    - Monobloc
    - Multibloc
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Format
- type: text
  name: traitement
  label: traitement
- type: list
  name: tags
  label: tags
- type: boolean
  name: series
  label: series
- type: boolean
  name: canonical_url
  label: canonical_url
- type: textarea
  name: description
  label: description
pages:
- content/products/banc-perron-stoop.md
- content/products/banquette-beam-double.md
- content/products/banquette-cantine-pm.md
- content/products/banquette-cantine.md
- content/products/banquette-duchesse.md
- content/products/banquette-elium.md
- content/products/canape-stamp-window.md
- content/products/chaise-elium.md
- content/products/chaise-obrac.md
- content/products/corbeille-asturias-lisse.md
- content/products/corbeille-asturias-vigipirate.md
- content/products/jardiniere-asturias-lisse.md
- content/products/table-vertable.md
- content/products/tabouret-elium.md
- content/products/totem-mineral.md
- content/products/transat-camah.md
- content/products/transat-mila.md
