---
label: Produit
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: boolean
  name: published
  label: published
- type: text
  name: designer
  label: designer
- type: text
  name: collection
  label: collection
- type: text
  name: category
  label: category
- type: text
  name: sub_category
  label: sub_category
- type: text
  name: gamme
  label: gamme
- type: text
  name: finitions
  label: finitions
- type: file
  name: cover_image
  label: cover_image
- type: image_gallery
  name: caroussel
  label: caroussel
- type: image_gallery
  name: filaire
  label: filaire
- type: text
  name: reference
  label: reference
- type: text
  name: materiau
  label: materiau
- type: number
  name: poids
  label: poids
- type: text
  name: dimensions
  label: dimensions
- type: text
  name: format
  label: format
- type: text
  name: traitement
  label: traitement
- type: text
  name: tags
  label: tags
- type: text
  name: description
  label: description
